version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: aitube-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: aitube

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7

    container_name: aitube-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

volumes:

  postgres_data: